name: Question
description: Ask a question about usage, configuration, or troubleshooting
title: "[Question]: "
labels: ["question", "needs-triage"]

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I searched existing issues and docs
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Installation/Deployment
        - Configuration
        - Troubleshooting
        - Performance/Monitoring
        - Integration
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Relevant details about your setup (redact credentials/secrets).
      placeholder: |
        - What you're trying to accomplish:
        - Eidos version (CLI `eidos version`, API image tag, or commit SHA):
        - Platform (eks/gke/aks/self-managed):
        - Kubernetes version:
        - OS + version, kernel:
        - GPU type (if applicable):
        - Commands you ran:
        - Output / errors:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Helpful links:
        - User guide: https://github.com/NVIDIA/cloud-native-stack/tree/main/docs/user-guide
        - Examples: https://github.com/NVIDIA/cloud-native-stack/tree/main/examples
        - API reference: https://github.com/NVIDIA/cloud-native-stack/blob/main/docs/integration/api-reference.md