#!/bin/bash

# NVSentinel Uninstallation Script
# Generated by Cloud Native Stack
# Timestamp: 2026-01-11T16:17:47Z
# Bundler Version: v0.12.4-next

set -e

echo "Uninstalling NVSentinel..."

# Uninstall Helm release
echo "Uninstalling NVSentinel Helm release..."
helm uninstall nvsentinel -n nvsentinel || true

# Wait for cleanup
echo "Waiting for resources to be cleaned up..."
sleep 10

# Optionally delete namespace
read -p "Do you want to delete the namespace nvsentinel? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    kubectl delete namespace nvsentinel --ignore-not-found=true
    echo "Namespace nvsentinel deleted."
else
    echo "Namespace nvsentinel preserved."
fi

echo "NVSentinel uninstallation complete!"
