# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Install E2E Testing Tools'
description: 'Installs development tools for E2E testing using the shared setup script'

# This action uses tools/setup-tools to ensure consistency between
# local development and CI environments. The same script, same versions,
# same installation logic - no more "works on my machine" issues.

runs:
  using: "composite"
  steps:
    - name: Cache development tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
      with:
        path: |
          /usr/local/bin/ctlptl
          /usr/local/bin/kind
          /usr/local/bin/kubectl
          /usr/local/bin/tilt
          /usr/local/bin/ko
          /usr/local/bin/helm
          /usr/local/bin/yq
        # Cache key based on .versions.yaml - invalidates when versions change
        # yamllint disable-line rule:line-length
        key: e2e-tools-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.versions.yaml') }}
        restore-keys: |
          e2e-tools-${{ runner.os }}-${{ runner.arch }}-

    - name: Install tools via setup-tools script
      shell: bash
      run: |
        # Use the shared setup script for consistency with local development
        # --auto: Non-interactive mode (auto-yes to all prompts)
        # --skip-go: Go is set up by actions/setup-go
        # --skip-docker: Docker is pre-installed on GitHub runners
        chmod +x tools/setup-tools
        AUTO_MODE=true ./tools/setup-tools --skip-go --skip-docker

    - name: Verify tool installations
      shell: bash
      run: |
        echo "=== Installed Tools ==="
        make tools-check
