#!/bin/bash

# Skyhook Operator Uninstallation Script
# Generated by Cloud Native Stack
# Timestamp: 2026-01-11T16:17:47Z
# Bundler Version: v0.12.4-next

set -e

echo "Uninstalling Skyhook Operator..."

# Delete Skyhook customizations if manifests directory exists
if [ -d "manifests" ]; then
  echo "Deleting Skyhook customizations..."
  kubectl delete -f manifests/ --ignore-not-found=true
fi

# Wait for cleanup
echo "Waiting for resources to be cleaned up..."
sleep 10

# Uninstall Helm release
echo "Uninstalling Skyhook Operator Helm release..."
helm uninstall skyhook -n skyhook || true

# Optionally delete namespace
read -p "Do you want to delete the namespace skyhook? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    kubectl delete namespace skyhook --ignore-not-found=true
    echo "Namespace skyhook deleted."
else
    echo "Namespace skyhook preserved."
fi

echo "Skyhook Operator uninstallation complete!"
