#!/bin/bash

# NVSentinel Installation Script
# Generated by CNS Eidos
# Timestamp: 2026-01-11T16:17:47Z
# Bundler Version: v0.12.4-next

set -e

echo "Installing NVSentinel..."

# Create namespace if it doesn't exist
kubectl create namespace nvsentinel --dry-run=client -o yaml | kubectl apply -f -

# Install NVSentinel using Helm
echo "Installing NVSentinel v0.6.0 using Helm..."
helm upgrade --install nvsentinel oci://ghcr.io/nvidia/nvsentinel \
  --namespace nvsentinel \
  --create-namespace \
  --version v0.6.0 \
  --timeout 15m \
  --wait

# Wait for NVSentinel pods to be ready
echo "Waiting for NVSentinel pods to be ready..."
kubectl wait --for=condition=ready --timeout=300s \
  pod -l app.kubernetes.io/name=nvsentinel \
  -n nvsentinel || true

echo "NVSentinel installation complete!"
echo ""
echo "To verify the installation:"
echo "  kubectl get pods -n nvsentinel"
echo "  kubectl get nodes  # Verify GPU nodes are visible"
echo ""
echo "To run validation:"
echo "  kubectl run nvsentinel-validation --image=curlimages/curl:latest -n nvsentinel --rm -it --restart=Never -- sh"
